### ISSUE TITLE
Comments: Allow trailing comments

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#172] opened 2020-09-21 21:38 UTC
I see that `erlfmt` removes _trailing_ comments (the best it can) and places them in a line "above". Why?

My reasoning is usually this: if it's _trailing_ it pertains to a single line. If it's above a line it "might" pertain to a block of code.

Examples follow:

```erlang
Value = Value0, % I want to signal intention (there's no conversion here!)
maps:get(face, Value)
```

and

```erlang
ok = and_there(i_was),

% You'll like this next one
_Commented = commenting_away_on_erlfmt(),
Dragon = when_all_of_a_sudden(),
Water = nothing_happened(),

Which = is_why()
```

**Comment by awalterschulze** [comment] 2020-09-22 18:58
Thank you for bringing this up.  Discussion on this is ongoing https://github.com/WhatsApp/erlfmt/pull/124

**Comment by paulo-ferraz-oliveira** [comment] 2020-10-28 12:26
This is no longer an issue, to me. Since I was the one that opened it, you're welcome to close it if there's no more work planned on top of it. (also #124 is already merged)

**Comment by awalterschulze** [comment] 2020-10-28 13:08
May I ask why this is no longer an issue for you?  That could be very interesting for future users raising the same issue
I just want to be clear that just because a formatting decision has been merged, does not mean it is done, see the Readme
https://github.com/WhatsApp/erlfmt/blob/master/doc/Readme.md#formatting-decisions

**Comment by paulo-ferraz-oliveira** [comment] 2020-10-28 15:30
Hi, @awalterschulze.

I see more value in a less-opinionated and more choice-oriented system, so I'm mainly testing integration with `rebar3_format` (at the moment). I do understand your decisions are motivated by a much broader scope than the one I have to deal with, and I will keep an eye on the developments in this project, in any case.

I still believe what you did (and are doing) is VERY useful and will help pave the way for future lib.s (that start from scratch, mainly) to keep a consistent code base in terms of format. In other words, what you're doing (again, very well!) steers a direction for "the whole Erlang community", but I feel it's important to be able to tweak certain stuff, so that the proper options can be put in practice, in the scope of a team.

(hopefully this answer provides insight into my comments, this morning, and I'd hate if anybody got sad over this 😄)

**Comment by paulo-ferraz-oliveira** [comment] 2020-10-28 15:53
I believe the work done, in #124, is enough for this issue to lose relevance.

**Comment by awalterschulze** [comment] 2020-10-28 16:35
Okay cool thanks, that is great to know :)

**Closed by awalterschulze** 2020-10-28 16:35 UTC
Labels: discussion

**Comment by awalterschulze** [comment] 2020-11-04 11:44
This can also be seen as a duplicate of https://github.com/WhatsApp/erlfmt/issues/219
